### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by chrstphrbls** [chrstphrbls/books#17]
> Failed tests but the Webapp is working fine

**Comment by chrstphrbls** [comment]
> failed tests

`======================================================================
FAIL: test_book_detail_view (books.tests.BookTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/books/tests.py", line 46, in test_book_detail_view
    self.assertEqual(response.status_code, 200)
AssertionError: 302 != 200

======================================================================
FAIL: test_book_list_view (books.tests.BookTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/books/tests.py", line 39, in test_book_list_view
    self.assertEqual(response.status_code, 200)
AssertionError: 302 != 200

======================================================================
FAIL: test_book_list_view_for_logged_in_user (books.tests.BookTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/books/tests.py", line 55, in test_book_list_view_for_logged_in_user
    self.assertEqual(response.status_code,200)
AssertionError: 302 != 200

======================================================================
FAIL: test_book_list_view_for_logged_out_user (books.tests.BookTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/books/tests.py", line 69, in test_book_list_view_for_logged_out_user
    self.assertContains(response,'Login In')
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 454, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'Login In' in response

----------------------------------------------------------------------
Ran 20 tests in 0.558s

FAILED   ##(failures=4)`

**Comment by chrstphrbls** [comment]
> fixing typo
![Image](https://user-images.githubusercontent.com/109645414/183334899-e815db66-0fef-490e-a1cf-876aae4c8e63.png)
